name: Generate 3D Profile Contributions

on:
  schedule:
    - cron: "0 0 * * 1"  # Every Monday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Graphs
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_USERNAME: Muhamash
          THEME: night-rainbow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit 3D Graphs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib/
          git commit -m "chore: update 3D contribution graphs" || echo "No changes to commit"
          git push
