name: Contribution Snake
on:
  schedule:
    - cron: "0 0 * * *"   # Daily
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Muhamash
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/*
      - uses: actions/checkout@v4
      - name: Commit snake SVGs
        run: |
          mkdir -p dist
          cp -r ${{ github.workspace }}/dist/* ./dist/ || true
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/*
          git commit -m "chore: update snake graph" || echo "no changes"
          git push
